[package]
name = "simple-translate-json"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evmap = "10.0.2"
include_dir = "0.7.3"
serde_json = "1.0.1"
sys-locale = "0.3.1"

